site_name: ansible-role-k3s Documentation
theme: "material"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: "#087da1"
    accent: "#00a889"
  font:
    text: "Source Sans Pro"

repo_name: "hadenlabs/ansible-role-k3s"
repo_url: "https://github.com/hadenlabs/ansible-role-k3s"
copyright: 'Copyright Â© 2021 <a href="https://hadenlabs.com">hadenlabs</a>'

google_analytics:
  - ""
  - "auto"
