---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install k3s package dependencies
  ansible.builtin.package:
    name: '{{ k3s_packages }}'
    state: present
  become: true
  register: install_k3s_packages
  when: k3s_packages is defined
  tags:
    - install
    - apt
    - update_cache
