---
- name: Create files k3s
  become: true
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: '{{ item.owner }}'
  with_items: '{{ _k3s_create_files | default({}) }}'
  when: _k3s_create_files is defined
